// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-2ejfzm6egtrq4QkzcgGYvwja0RUsGsA',
    appId: '1:944808040608:web:3ae3e4316e441b7fc9d1c5',
    messagingSenderId: '944808040608',
    projectId: 'prakflutterfirebase-9b65b',
    authDomain: 'prakflutterfirebase-9b65b.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-9b65b.appspot.com',
    measurementId: 'G-1WKC6CCDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGgjxL1xpS1vdWdQGteMwdEkzGQgGMwVk',
    appId: '1:944808040608:android:e9257a8b4b79b2dfc9d1c5',
    messagingSenderId: '944808040608',
    projectId: 'prakflutterfirebase-9b65b',
    storageBucket: 'prakflutterfirebase-9b65b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZch2Hl_772mjyoRTEbKvSIobnMW-UK4k',
    appId: '1:944808040608:ios:0b48ee7f6dc1bfe3c9d1c5',
    messagingSenderId: '944808040608',
    projectId: 'prakflutterfirebase-9b65b',
    storageBucket: 'prakflutterfirebase-9b65b.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZch2Hl_772mjyoRTEbKvSIobnMW-UK4k',
    appId: '1:944808040608:ios:0b48ee7f6dc1bfe3c9d1c5',
    messagingSenderId: '944808040608',
    projectId: 'prakflutterfirebase-9b65b',
    storageBucket: 'prakflutterfirebase-9b65b.appspot.com',
    iosBundleId: 'com.example.praktikum6',
  );
}
